<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" ignored="0" total="21" passed="15">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="2676" started-at="2020-02-17T15:08:57Z" finished-at="2020-02-17T15:09:00Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="2676" started-at="2020-02-17T15:08:57Z" finished-at="2020-02-17T15:09:00Z">
      <class name="by.epam.project.service.UserServiceTest">
        <test-method status="PASS" signature="findByUsernameAndPass(java.lang.String, java.lang.String)[pri:0, instance:by.epam.project.service.UserServiceTest@1a407d53]" name="findByUsernameAndPass" duration-ms="15" started-at="2020-02-17T18:09:00Z" data-provider="findByUsernameAndPass" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Anastasiya]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[210789]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findByUsernameAndPass -->
        <test-method status="FAIL" signature="findByUsernameAndPass(java.lang.String, java.lang.String)[pri:0, instance:by.epam.project.service.UserServiceTest@1a407d53]" name="findByUsernameAndPass" duration-ms="3" started-at="2020-02-17T18:09:00Z" data-provider="findByUsernameAndPass" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[werf]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[4454t]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 0, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at by.epam.project.service.UserServiceTest.findByUsernameAndPass(UserServiceTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findByUsernameAndPass -->
        <test-method status="FAIL" signature="findByUsernameAndPass(java.lang.String, java.lang.String)[pri:0, instance:by.epam.project.service.UserServiceTest@1a407d53]" name="findByUsernameAndPass" duration-ms="3" started-at="2020-02-17T18:09:00Z" data-provider="findByUsernameAndPass" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ghyjj]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ererf]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 0, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at by.epam.project.service.UserServiceTest.findByUsernameAndPass(UserServiceTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findByUsernameAndPass -->
        <test-method status="PASS" signature="testFindById(int, java.lang.String)[pri:0, instance:by.epam.project.service.UserServiceTest@1a407d53]" name="testFindById" duration-ms="3" started-at="2020-02-17T18:09:00Z" data-provider="testServiceFindUserById" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Nastya]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFindById -->
        <test-method status="PASS" signature="testFindById(int, java.lang.String)[pri:0, instance:by.epam.project.service.UserServiceTest@1a407d53]" name="testFindById" duration-ms="3" started-at="2020-02-17T18:09:00Z" data-provider="testServiceFindUserById" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Anna]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFindById -->
        <test-method status="PASS" signature="testFindById(int, java.lang.String)[pri:0, instance:by.epam.project.service.UserServiceTest@1a407d53]" name="testFindById" duration-ms="4" started-at="2020-02-17T18:09:00Z" data-provider="testServiceFindUserById" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Igorik]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFindById -->
        <test-method status="PASS" signature="testFindUserByEmailAndPassword(java.lang.String, java.lang.String)[pri:0, instance:by.epam.project.service.UserServiceTest@1a407d53]" name="testFindUserByEmailAndPassword" duration-ms="6" started-at="2020-02-17T18:09:00Z" data-provider="testFindUserByEmailAndPassword" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[shpakavaa@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[210789]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFindUserByEmailAndPassword -->
      </class> <!-- by.epam.project.service.UserServiceTest -->
      <class name="by.epam.project.service.TicketServiceTest">
        <test-method status="FAIL" signature="testFindOrderById(int, int)[pri:0, instance:by.epam.project.service.TicketServiceTest@6aaa5eb0]" name="testFindOrderById" duration-ms="20" started-at="2020-02-17T18:09:00Z" data-provider="testFindOrderById" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <exception class="by.epam.project.exception.ServiceException">
            <message>
              <![CDATA[by.epam.project.exception.DaoException: by.epam.project.exception.ServiceException: by.epam.project.exception.DaoException: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order WHERE order_id=1' at line 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.epam.project.exception.ServiceException: by.epam.project.exception.DaoException: by.epam.project.exception.ServiceException: by.epam.project.exception.DaoException: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order WHERE order_id=1' at line 1
	at by.epam.project.service.impl.TicketServiceImpl.findTicketById(TicketServiceImpl.java:68)
	at by.epam.project.service.TicketServiceTest.testFindOrderById(TicketServiceTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: by.epam.project.exception.DaoException: by.epam.project.exception.ServiceException: by.epam.project.exception.DaoException: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order WHERE order_id=1' at line 1
	at by.epam.project.dao.impl.TicketDaoImpl.findById(TicketDaoImpl.java:166)
	at by.epam.project.dao.impl.TicketDaoImpl.findById(TicketDaoImpl.java:14)
	at by.epam.project.service.impl.TicketServiceImpl.findTicketById(TicketServiceImpl.java:66)
	... 31 more
Caused by: by.epam.project.exception.ServiceException: by.epam.project.exception.DaoException: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order WHERE order_id=1' at line 1
	at by.epam.project.service.impl.OrderServiceImpl.findOrderById(OrderServiceImpl.java:79)
	at by.epam.project.dao.impl.TicketDaoImpl.findOrderById(TicketDaoImpl.java:57)
	at by.epam.project.dao.impl.TicketDaoImpl.findById(TicketDaoImpl.java:158)
	... 33 more
Caused by: by.epam.project.exception.DaoException: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order WHERE order_id=1' at line 1
	at by.epam.project.dao.impl.OrderDaoImpl.findById(OrderDaoImpl.java:227)
	at by.epam.project.dao.impl.OrderDaoImpl.findById(OrderDaoImpl.java:24)
	at by.epam.project.service.impl.OrderServiceImpl.findOrderById(OrderServiceImpl.java:77)
	... 35 more
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order WHERE order_id=1' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	at by.epam.project.dao.impl.OrderDaoImpl.findById(OrderDaoImpl.java:211)
	... 37 more
]]>
            </full-stacktrace>
          </exception> <!-- by.epam.project.exception.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFindOrderById -->
      </class> <!-- by.epam.project.service.TicketServiceTest -->
      <class name="by.epam.project.service.EventTypeServiceTest">
        <test-method status="FAIL" signature="findByNameOrWordInName(java.lang.String, int)[pri:0, instance:by.epam.project.service.EventTypeServiceTest@22f71333]" name="findByNameOrWordInName" duration-ms="2" started-at="2020-02-17T18:09:00Z" data-provider="findByNameOrWordInName" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[concert]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <exception class="by.epam.project.exception.ServiceException">
            <message>
              <![CDATA[by.epam.project.exception.DaoException: Error in the requesting to the database.]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.epam.project.exception.ServiceException: by.epam.project.exception.DaoException: Error in the requesting to the database.
	at by.epam.project.service.impl.EventTypeServiceImpl.findByNameOrWordInNameWithLimit(EventTypeServiceImpl.java:80)
	at by.epam.project.service.EventTypeServiceTest.findByNameOrWordInName(EventTypeServiceTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: by.epam.project.exception.DaoException: Error in the requesting to the database.
	at by.epam.project.dao.impl.EventTypeDaoImpl.closeResultSet(EventTypeDaoImpl.java:317)
	at by.epam.project.dao.impl.EventTypeDaoImpl.findByNameOrWordInNameWithLimit(EventTypeDaoImpl.java:168)
	at by.epam.project.service.impl.EventTypeServiceImpl.findByNameOrWordInNameWithLimit(EventTypeServiceImpl.java:78)
	... 31 more
]]>
            </full-stacktrace>
          </exception> <!-- by.epam.project.exception.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findByNameOrWordInName -->
      </class> <!-- by.epam.project.service.EventTypeServiceTest -->
      <class name="by.epam.project.service.UserCommentServiceTest">
        <test-method status="PASS" signature="testServiceFindUserCommentsById(int, java.lang.String)[pri:0, instance:by.epam.project.service.UserCommentServiceTest@3498ed]" name="testServiceFindUserCommentsById" duration-ms="12" started-at="2020-02-17T18:09:00Z" data-provider="testServiceFindUserCommentsById" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Cool]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testServiceFindUserCommentsById -->
      </class> <!-- by.epam.project.service.UserCommentServiceTest -->
      <class name="by.epam.project.connection.ConnectionPoolTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:by.epam.project.connection.ConnectionPoolTest@1554909b]" name="setUp" is-config="true" duration-ms="2475" started-at="2020-02-17T18:08:58Z" finished-at="2020-02-17T18:09:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testCheckPoolSize()[pri:0, instance:by.epam.project.connection.ConnectionPoolTest@1554909b]" name="testCheckPoolSize" duration-ms="3" started-at="2020-02-17T18:09:00Z" finished-at="2020-02-17T18:09:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheckPoolSize -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:by.epam.project.connection.ConnectionPoolTest@1554909b]" name="tearDown" is-config="true" duration-ms="0" started-at="2020-02-17T18:09:00Z" finished-at="2020-02-17T18:09:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- by.epam.project.connection.ConnectionPoolTest -->
      <class name="by.epam.project.service.EventServiceTest">
        <test-method status="FAIL" signature="testServiceFindEventById(int, int)[pri:0, instance:by.epam.project.service.EventServiceTest@6cd8737]" name="testServiceFindEventById" duration-ms="21" started-at="2020-02-17T18:09:00Z" data-provider="testServiceFindEventById" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found [EventType {eventTypeId= 1, eventName= concert, eventAddress= Minsk, description=concert, imageURL=C:UsersDELLDesktopУчебаHTP14Finalyyy.png}]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [EventType {eventTypeId= 1, eventName= concert, eventAddress= Minsk, description=concert, imageURL=C:UsersDELLDesktopУчебаHTP14Finalyyy.png}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at by.epam.project.service.EventServiceTest.testServiceFindEventById(EventServiceTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testServiceFindEventById -->
      </class> <!-- by.epam.project.service.EventServiceTest -->
      <class name="by.epam.project.RegistrationTest">
        <test-method status="PASS" signature="validationPasswordTest(java.lang.String, boolean)[pri:0, instance:by.epam.project.RegistrationTest@6bf256fa]" name="validationPasswordTest" duration-ms="0" started-at="2020-02-17T18:09:00Z" data-provider="testPassword" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[A1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationPasswordTest -->
        <test-method status="PASS" signature="validationPasswordTest(java.lang.String, boolean)[pri:0, instance:by.epam.project.RegistrationTest@6bf256fa]" name="validationPasswordTest" duration-ms="0" started-at="2020-02-17T18:09:00Z" data-provider="testPassword" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[djfH8jshf]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationPasswordTest -->
        <test-method status="PASS" signature="validationPasswordTest(java.lang.String, boolean)[pri:0, instance:by.epam.project.RegistrationTest@6bf256fa]" name="validationPasswordTest" duration-ms="0" started-at="2020-02-17T18:09:00Z" data-provider="testPassword" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Nastya1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationPasswordTest -->
        <test-method status="PASS" signature="validationPasswordTest(java.lang.String, boolean)[pri:0, instance:by.epam.project.RegistrationTest@6bf256fa]" name="validationPasswordTest" duration-ms="0" started-at="2020-02-17T18:09:00Z" data-provider="testPassword" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ddfkgkgkgkgkgkgksdff]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationPasswordTest -->
        <test-method status="PASS" signature="validationUsernameTest(java.lang.String, boolean)[pri:0, instance:by.epam.project.RegistrationTest@6bf256fa]" name="validationUsernameTest" duration-ms="0" started-at="2020-02-17T18:09:00Z" data-provider="testLogin" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[annaan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationUsernameTest -->
        <test-method status="PASS" signature="validationUsernameTest(java.lang.String, boolean)[pri:0, instance:by.epam.project.RegistrationTest@6bf256fa]" name="validationUsernameTest" duration-ms="0" started-at="2020-02-17T18:09:00Z" data-provider="testLogin" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[vf]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationUsernameTest -->
        <test-method status="PASS" signature="validationUsernameTest(java.lang.String, boolean)[pri:0, instance:by.epam.project.RegistrationTest@6bf256fa]" name="validationUsernameTest" duration-ms="0" started-at="2020-02-17T18:09:00Z" data-provider="testLogin" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Bg_jagsw]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationUsernameTest -->
        <test-method status="PASS" signature="validationUsernameTest(java.lang.String, boolean)[pri:0, instance:by.epam.project.RegistrationTest@6bf256fa]" name="validationUsernameTest" duration-ms="0" started-at="2020-02-17T18:09:00Z" data-provider="testLogin" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[      ]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationUsernameTest -->
      </class> <!-- by.epam.project.RegistrationTest -->
      <class name="by.epam.project.service.OrderServiceTest">
        <test-method status="FAIL" signature="testServiceFindOrderById(int, java.lang.String)[pri:0, instance:by.epam.project.service.OrderServiceTest@13969fbe]" name="testServiceFindOrderById" duration-ms="47" started-at="2020-02-17T18:09:00Z" data-provider="testServiceFindOrderById" finished-at="2020-02-17T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[balcon]]>
              </value>
            </param>
          </params>
          <exception class="by.epam.project.exception.ServiceException">
            <message>
              <![CDATA[by.epam.project.exception.DaoException: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order WHERE order_id=1' at line 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.epam.project.exception.ServiceException: by.epam.project.exception.DaoException: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order WHERE order_id=1' at line 1
	at by.epam.project.service.impl.OrderServiceImpl.findOrderById(OrderServiceImpl.java:79)
	at by.epam.project.service.OrderServiceTest.testServiceFindOrderById(OrderServiceTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: by.epam.project.exception.DaoException: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order WHERE order_id=1' at line 1
	at by.epam.project.dao.impl.OrderDaoImpl.findById(OrderDaoImpl.java:227)
	at by.epam.project.dao.impl.OrderDaoImpl.findById(OrderDaoImpl.java:24)
	at by.epam.project.service.impl.OrderServiceImpl.findOrderById(OrderServiceImpl.java:77)
	... 31 more
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order WHERE order_id=1' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	at by.epam.project.dao.impl.OrderDaoImpl.findById(OrderDaoImpl.java:211)
	... 33 more
]]>
            </full-stacktrace>
          </exception> <!-- by.epam.project.exception.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testServiceFindOrderById -->
      </class> <!-- by.epam.project.service.OrderServiceTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
